# Generated by Django 4.0.6 on 2022-07-25 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patient_avail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='avail',
        ),
    ]
