# Generated by Django 4.0.6 on 2022-07-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_remove_doctors_profile_pic_doctors_profilepic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timing', models.CharField(blank=True, choices=[('10AM - 11AM', '10AM - 11AM'), ('11AM - 12PM', '11AM TO 12PM'), ('12PM - 1PM', '12PM - 1PM'), ('2PM - 3PM', '2PM - 3PM'), ('3PM - 4PM', '3PM - 4PM')], max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='profilepic',
        ),
        migrations.AddField(
            model_name='doctors',
            name='time',
            field=models.ManyToManyField(blank=True, to='doctor.time'),
        ),
    ]
