# Generated by Django 4.0.6 on 2022-07-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_time_remove_doctors_profilepic_doctors_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='price',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
    ]
