# Generated by Django 4.0.6 on 2022-07-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_avail'),
    ]

    operations = [
        migrations.AddField(
            model_name='avail',
            name='time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
