# Generated by Django 4.0.6 on 2022-07-24 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_avail_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='time',
        ),
    ]
