# Generated by Django 4.0.6 on 2022-07-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_remove_doctors_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
