# Generated by Django 4.0.6 on 2022-07-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0013_alter_doctors_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='avail',
            name='patientname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
