# Generated by Django 4.0.6 on 2022-07-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0016_avail_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='avail',
            name='profilepic',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
