# Generated by Django 4.0.6 on 2022-07-24 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0018_remove_avail_profilepic_doctors_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='profilepic',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='', verbose_name='images/'),
        ),
    ]
