# Generated by Django 4.0.6 on 2022-07-24 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0019_alter_doctors_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='profilepic',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=''),
        ),
    ]
