# Generated by Django 4.0.6 on 2022-07-25 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0020_alter_doctors_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='specialization',
            field=models.CharField(blank=True, choices=[('CARDIO', 'CARDIO'), ('ENT', 'ENT'), ('Anesthesiology', 'Anesthesiology'), ('Dermatology', 'Dermatology'), ('Orthopedic', 'Orthopedic')], max_length=100, null=True),
        ),
    ]
