# Generated by Django 4.0.6 on 2022-07-25 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0021_alter_doctors_specialization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avail',
            name='patient',
        ),
    ]
